// Generates supabase/migrations/0007_ltr_market_premium.sql — seeds the LTR premium
// notes (ltrNote / sourceUrl / confidence) that were stripped from the client bundle
// (SPEC_LTR §5) into market_premium, so Pro/Investor see them again via get_market_intel.
//
//   node supabase/seed/seed_ltr_premium.mjs
//
// The notes live in dedicated ltr_note / ltr_source_url columns so they NEVER clobber
// the existing flip/STR benchmark_note / source_url on shared market ids (many LTR
// markets are also flip/STR). The pre-strip data is recovered from git (commit 45fe05a,
// the last commit before the LTR strip).

import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const PRE_STRIP_REF = "45fe05a"; // last commit with ltrNote/sourceUrl in the bundle

const src = execSync(`git show ${PRE_STRIP_REF}:docs/src/js/markets.js`, {
  encoding: "utf8",
  maxBuffer: 64 * 1024 * 1024,
  cwd: join(here, "..", ".."),
});
const mod = await import("data:text/javascript," + encodeURIComponent(src));

const rows = Object.entries(mod.LTR_MARKETS)
  .map(([id, m]) => ({ id, note: m.ltrNote || null, url: m.sourceUrl || null, conf: m.confidence || null }))
  .filter((r) => r.note || r.url); // only seed markets that actually have premium notes

const esc = (s) => (s == null ? "null" : "'" + String(s).replace(/'/g, "''") + "'");
const values = rows.map((r) => `  (${esc(r.id)}, ${esc(r.note)}, ${esc(r.url)}, ${esc(r.conf)})`).join(",\n");

const sql = `-- ───────────────────────────────────────────────────────────────────────────
-- Deal Screener · 0007: LTR premium notes (re-seat the stripped moat server-side)
-- ───────────────────────────────────────────────────────────────────────────
-- The LTR analyst notes (ltrNote) + data sources (sourceUrl) were stripped from the
-- client bundle (SPEC_LTR §5 — closed the leak). This re-seats them server-side in
-- market_premium so Pro/Investor see them again through get_market_intel(), gated
-- exactly like the flip/STR depth (Pro = note + source; Investor = confidence).
--
-- Dedicated ltr_note / ltr_source_url columns so shared market ids keep their flip/STR
-- benchmark_note / source_url intact (the upsert touches only the LTR columns).
--
-- HOW TO RUN: Supabase dashboard → SQL Editor → paste → Run. (After 0003 + 0004.)
-- Generated by supabase/seed/seed_ltr_premium.mjs from bundle commit ${PRE_STRIP_REF}.
-- ${rows.length} LTR markets with premium notes.
-- ───────────────────────────────────────────────────────────────────────────

alter table public.market_premium add column if not exists ltr_note       text;
alter table public.market_premium add column if not exists ltr_source_url text;

-- Extend get_market_intel to return the LTR fields (Pro-gated). The return TABLE
-- signature changes, so drop + recreate (CREATE OR REPLACE can't alter the shape).
drop function if exists public.get_market_intel(text[]);

create function public.get_market_intel(p_market_ids text[])
returns table (
  market_id       text,
  rehab_note      text,
  str_viability   text,
  str_rev_low     integer,
  str_rev_high    integer,
  benchmark_note  text,
  regulatory_note text,
  regulatory_risk text,
  confidence      text,
  source_url      text,
  ltr_note        text,
  ltr_source_url  text
)
language plpgsql
stable
security definer
set search_path = public
as $func$
declare
  v_tier text := public.current_tier();
  v_pro  boolean := (v_tier = 'pro');
begin
  if v_tier not in ('investor','pro') then
    return;
  end if;

  return query
    select
      mp.market_id,
      case when v_pro then mp.rehab_note      else null end,
      mp.str_viability,
      mp.str_rev_low,
      mp.str_rev_high,
      case when v_pro then mp.benchmark_note  else null end,
      case when v_pro then mp.regulatory_note else null end,
      mp.regulatory_risk,
      mp.confidence,
      case when v_pro then mp.source_url      else null end,
      case when v_pro then mp.ltr_note        else null end,
      case when v_pro then mp.ltr_source_url  else null end
    from public.market_premium mp
    where mp.market_id = any (p_market_ids);
end;
$func$;

revoke all on function public.get_market_intel(text[]) from public, anon;
grant execute on function public.get_market_intel(text[]) to authenticated;

-- Seed the LTR premium. Upsert touches ONLY the LTR columns (+ confidence when the
-- existing row has none) so flip/STR depth on shared ids is preserved.
insert into public.market_premium (market_id, ltr_note, ltr_source_url, confidence) values
${values}
on conflict (market_id) do update set
  ltr_note       = excluded.ltr_note,
  ltr_source_url = excluded.ltr_source_url,
  confidence     = coalesce(public.market_premium.confidence, excluded.confidence),
  updated_at     = now();
`;

const out = join(here, "..", "migrations", "0007_ltr_market_premium.sql");
writeFileSync(out, sql);
console.log(`Wrote ${out}\n${rows.length} LTR markets seeded.`);
