// One-off seed generator: extracts the PREMIUM "depth" fields out of the client
// bundle (markets.js) and emits 0004_seed_market_premium.sql to populate
// public.market_premium. Never hand-transcribe the markets — run this.
//
//   node supabase/seed/seed_market_premium.mjs
//
// Precedence on collision (confidence / sourceUrl present on both the flip and
// the str object for a slug): STR wins, flip is the fallback — STR entries carry
// the richer regulatory context. Only slugs with at least one premium value get
// a row; markets with no depth are skipped (get_market_intel returns nothing).

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const OUT = join(here, '..', 'migrations', '0004_seed_market_premium.sql');

// markets.js is an ES module with no imports; load it as ESM via a data: URL so
// Node doesn't mis-parse the .js extension as CommonJS.
const marketsSrc = readFileSync(
  join(here, '..', '..', 'docs', 'src', 'js', 'markets.js'), 'utf8');
const { FLIP_MARKETS, STR_MARKETS } =
  await import('data:text/javascript,' + encodeURIComponent(marketsSrc));

// SQL literal helpers
const q = (v) =>
  v === undefined || v === null || v === '' ? 'null' : `'${String(v).replace(/'/g, "''")}'`;
const n = (v) =>
  v === undefined || v === null || v === '' || Number.isNaN(Number(v)) ? 'null' : String(Math.round(Number(v)));

// Merge premium fields from both sources, keyed by slug.
const rows = new Map(); // slug -> column object
const ensure = (slug) => {
  if (!rows.has(slug)) {
    rows.set(slug, {
      rehab_note: null, str_viability: null, str_rev_low: null, str_rev_high: null,
      benchmark_note: null, regulatory_note: null, regulatory_risk: null,
      confidence: null, source_url: null,
    });
  }
  return rows.get(slug);
};

for (const [slug, m] of Object.entries(FLIP_MARKETS || {})) {
  if (!m) continue;
  const r = ensure(slug);
  if (m.rehabNote)   r.rehab_note   = m.rehabNote;
  if (m.strViability) r.str_viability = m.strViability;
  if (m.strRevLow  != null) r.str_rev_low  = m.strRevLow;
  if (m.strRevHigh != null) r.str_rev_high = m.strRevHigh;
  if (m.confidence) r.confidence = m.confidence;   // flip fallback (STR overwrites below)
  if (m.sourceUrl)  r.source_url = m.sourceUrl;
}

for (const [slug, m] of Object.entries(STR_MARKETS || {})) {
  if (!m) continue;
  const r = ensure(slug);
  if (m.benchmarkNote)   r.benchmark_note  = m.benchmarkNote;
  if (m.regulatoryNote)  r.regulatory_note = m.regulatoryNote;
  if (m.regulatoryRisk)  r.regulatory_risk = m.regulatoryRisk;
  if (m.confidence) r.confidence = m.confidence;   // STR-preferred
  if (m.sourceUrl)  r.source_url = m.sourceUrl;
}

// Drop slugs that ended up with no premium content at all.
const cols = ['rehab_note','str_viability','str_rev_low','str_rev_high',
  'benchmark_note','regulatory_note','regulatory_risk','confidence','source_url'];
const numericCols = new Set(['str_rev_low','str_rev_high']);

const lines = [];
let kept = 0;
for (const [slug, r] of [...rows.entries()].sort((a, b) => a[0].localeCompare(b[0]))) {
  const hasAny = cols.some((c) => r[c] != null && r[c] !== '');
  if (!hasAny) continue;
  kept++;
  const vals = [q(slug), ...cols.map((c) => (numericCols.has(c) ? n(r[c]) : q(r[c])))];
  lines.push(
    `insert into public.market_premium (market_id, ${cols.join(', ')}) values (${vals.join(', ')})\n` +
    `  on conflict (market_id) do update set ${cols.map((c) => `${c} = excluded.${c}`).join(', ')}, updated_at = now();`
  );
}

const header =
`-- ───────────────────────────────────────────────────────────────────────────
-- Deal Screener · Phase 1b: seed market_premium (GENERATED — do not hand-edit)
-- Generated by supabase/seed/seed_market_premium.mjs from markets.js.
-- ${kept} markets with premium depth. Run after 0003. Idempotent (upsert).
-- ───────────────────────────────────────────────────────────────────────────\n\n`;

writeFileSync(OUT, header + lines.join('\n') + '\n');
console.log(`Wrote ${kept} market_premium rows to ${OUT}`);
console.log(`(FLIP_MARKETS: ${Object.keys(FLIP_MARKETS || {}).length}, STR_MARKETS: ${Object.keys(STR_MARKETS || {}).length})`);
