-- ───────────────────────────────────────────────────────────────────────────
-- Deal Screener · 0007: LTR premium notes (re-seat the stripped moat server-side)
-- ───────────────────────────────────────────────────────────────────────────
-- The LTR analyst notes (ltrNote) + data sources (sourceUrl) were stripped from the
-- client bundle (SPEC_LTR §5 — closed the leak). This re-seats them server-side in
-- market_premium so Pro/Investor see them again through get_market_intel(), gated
-- exactly like the flip/STR depth (Pro = note + source; Investor = confidence).
--
-- Dedicated ltr_note / ltr_source_url columns so shared market ids keep their flip/STR
-- benchmark_note / source_url intact (the upsert touches only the LTR columns).
--
-- HOW TO RUN: Supabase dashboard → SQL Editor → paste → Run. (After 0003 + 0004.)
-- Generated by supabase/seed/seed_ltr_premium.mjs from bundle commit 45fe05a.
-- 113 LTR markets with premium notes.
-- ───────────────────────────────────────────────────────────────────────────

alter table public.market_premium add column if not exists ltr_note       text;
alter table public.market_premium add column if not exists ltr_source_url text;

-- Extend get_market_intel to return the LTR fields (Pro-gated). The return TABLE
-- signature changes, so drop + recreate (CREATE OR REPLACE can't alter the shape).
drop function if exists public.get_market_intel(text[]);

create function public.get_market_intel(p_market_ids text[])
returns table (
  market_id       text,
  rehab_note      text,
  str_viability   text,
  str_rev_low     integer,
  str_rev_high    integer,
  benchmark_note  text,
  regulatory_note text,
  regulatory_risk text,
  confidence      text,
  source_url      text,
  ltr_note        text,
  ltr_source_url  text
)
language plpgsql
stable
security definer
set search_path = public
as $func$
declare
  v_tier text := public.current_tier();
  v_pro  boolean := (v_tier = 'pro');
begin
  if v_tier not in ('investor','pro') then
    return;
  end if;

  return query
    select
      mp.market_id,
      case when v_pro then mp.rehab_note      else null end,
      mp.str_viability,
      mp.str_rev_low,
      mp.str_rev_high,
      case when v_pro then mp.benchmark_note  else null end,
      case when v_pro then mp.regulatory_note else null end,
      mp.regulatory_risk,
      mp.confidence,
      case when v_pro then mp.source_url      else null end,
      case when v_pro then mp.ltr_note        else null end,
      case when v_pro then mp.ltr_source_url  else null end
    from public.market_premium mp
    where mp.market_id = any (p_market_ids);
end;
$func$;

revoke all on function public.get_market_intel(text[]) from public, anon;
grant execute on function public.get_market_intel(text[]) to authenticated;

-- Seed the LTR premium. Upsert touches ONLY the LTR columns (+ confidence when the
-- existing row has none) so flip/STR depth on shared ids is preserved.
insert into public.market_premium (market_id, ltr_note, ltr_source_url, confidence) values
  ('augusta-ga', 'Fort Eisenhower, healthcare, cyber employment, and medical students create steady demand with relatively investor-friendly rent-to-price ratios.', 'https://www.rentcafe.com/average-rent-market-trends/us/ga/augusta/', 'High'),
  ('cape-coral-fl', 'Single-family rental demand is tied to retirees, families, and Fort Myers spillover, but hurricane risk and added supply have softened rents.', 'https://www.zumper.com/rent-research/cape-coral-fl', 'Medium'),
  ('charleston-sc', 'Tourism, port employment, healthcare, and high-income in-migration support premium rents, but acquisition prices keep ratios tight.', 'https://www.zumper.com/rent-research/charleston-sc', 'High'),
  ('clarksville-tn', 'Fort Campbell and Nashville spillover create steady renter demand, but new supply and military turnover require conservative vacancy assumptions.', 'https://www.zumper.com/rent-research/clarksville-tn', 'High'),
  ('columbia-sc', 'Rental demand is supported by the University of South Carolina, state government, Fort Jackson, and a broad affordable renter base.', 'https://www.rentcafe.com/average-rent-market-trends/us/sc/columbia/', 'High'),
  ('columbus-ga', 'Fort Moore and regional healthcare support steady 3BR demand, while lower incomes make rent collection and property condition important.', 'https://www.zumper.com/rent-research/columbus-ga', 'Medium'),
  ('durham-nc', 'Rental demand is anchored by Duke, RTP, healthcare, and tech employment, though new apartment supply has softened rent growth.', 'https://www.rentcafe.com/average-rent-market-trends/us/nc/durham/', 'High'),
  ('fayetteville-nc', 'Fort Liberty creates consistent renter demand, but tenant turnover and military-cycle vacancy should be underwritten conservatively.', 'https://www.zumper.com/rent-research/fayetteville-nc', 'High'),
  ('fort-lauderdale-fl', 'Broward renter demand is supported by coastal jobs, retirees, and Miami spillover, though affordability and insurance costs constrain returns.', 'https://www.rentcafe.com/average-rent-market-trends/us/fl/fort-lauderdale/', 'High'),
  ('greensboro-nc', 'Triad renters are value-oriented, with demand supported by healthcare, universities, logistics, and a large affordable single-family rental base.', 'https://www.rentcafe.com/average-rent-market-trends/us/nc/greensboro/', 'High'),
  ('greenville-sc', 'Manufacturing, healthcare, downtown growth, and in-migration support demand, but elevated prices have weakened SFR cash-flow spreads.', 'https://www.rentcafe.com/average-rent-market-trends/us/sc/greenville/', 'High'),
  ('huntsville-al', 'Aerospace, defense, and tech jobs support demand, but heavy new apartment supply has pushed vacancies higher and softened rent growth.', 'https://www.rentcafe.com/average-rent-market-trends/us/al/huntsville/', 'High'),
  ('knoxville-tn', 'University of Tennessee, healthcare, in-migration, and limited affordable housing keep rental demand strong relative to local incomes.', 'https://www.rentcafe.com/average-rent-market-trends/us/tn/knoxville/', 'High'),
  ('macon-ga', 'Affordable rents and low entry prices can work for cash flow, but submarket selection and tenant quality drive outcomes.', 'https://www.zumper.com/rent-research/macon-ga', 'Medium'),
  ('miami-fl', 'Miami has deep renter demand from international migration, tourism, healthcare, and finance, but high prices and supply additions have cooled rent growth.', 'https://www.rentcafe.com/average-rent-market-trends/us/fl/miami/', 'High'),
  ('mobile-al', 'Port, shipbuilding, healthcare, and low-cost housing support cash flow, while storm exposure and tenant screening remain key risks.', 'https://www.rentcafe.com/average-rent-market-trends/us/al/mobile/', 'High'),
  ('montgomery-al', 'State government, Maxwell-Gunter AFB, healthcare, and affordability support renter demand, but neighborhood quality varies materially.', 'https://www.rentcafe.com/average-rent-market-trends/us/al/montgomery/', 'Medium'),
  ('norfolk-va', 'Naval Station Norfolk, Old Dominion University, port employment, and medical demand support rentals, with flood-zone risk affecting underwriting.', 'https://www.rentcafe.com/average-rent-market-trends/us/va/norfolk/', 'High'),
  ('pensacola-fl', 'Military, healthcare, beach-adjacent lifestyle demand, and affordability support rentals, while insurance and storm exposure affect net returns.', 'https://www.rentcafe.com/average-rent-market-trends/us/fl/pensacola/', 'High'),
  ('richmond-va', 'VCU, healthcare, state government, finance, and young-professional demand support rents, especially near The Fan, Museum District, and downtown.', 'https://www.rentcafe.com/average-rent-market-trends/us/va/richmond/', 'High'),
  ('sarasota-fl', 'Retiree and lifestyle demand supports premium rents, but very high acquisition prices and recent rent softness make cash flow difficult.', 'https://www.zumper.com/rent-research/sarasota-fl', 'High'),
  ('savannah-ga', 'Port, tourism, military, and SCAD demand keep renter depth strong, though new supply and affordability pressure have cooled rent growth.', 'https://www.zumper.com/rent-research/savannah-ga', 'High'),
  ('spartanburg-sc', 'BMW-supplier employment, logistics, and Greenville spillover support renter demand, with stronger cash flow in 3BR workforce housing.', 'https://www.zumper.com/rent-research/spartanburg-sc', 'Medium'),
  ('tallahassee-fl', 'Florida State, FAMU, state government, and student housing create steady demand but higher turnover than typical family-renter markets.', 'https://www.rentcafe.com/average-rent-market-trends/us/fl/leon-county/tallahassee/', 'High'),
  ('virginia-beach-va', 'Military, tourism, healthcare, and coastal lifestyle demand support 3BR rentals, with stronger rents near beach and military employment nodes.', 'https://www.zumper.com/rent-research/virginia-beach-va', 'High'),
  ('west-palm-beach-fl', 'Finance, healthcare, retirees, and Palm Beach County in-migration support rents, but high insurance and taxes require conservative underwriting.', 'https://www.rentcafe.com/average-rent-market-trends/us/fl/west-palm-beach/', 'High'),
  ('wilmington-nc', 'Coastal lifestyle demand, UNCW, healthcare, and limited close-in housing support rents, while insurance and home prices pressure cash flow.', 'https://www.rentcafe.com/average-rent-market-trends/us/nc/wilmington/', 'High'),
  ('winston-salem-nc', 'Demand is steady from healthcare, universities, and affordable workforce renters, with 3BR houses generally underwriting better than small apartments.', 'https://www.zumper.com/rent-research/winston-salem-nc', 'Medium'),
  ('amarillo-tx', 'Stable Panhandle economy, low home prices, and tight rental supply create favorable cash-flow conditions for buy-and-hold investors in Amarillo.', null, 'Medium'),
  ('baton-rouge-la', 'LSU, state government, and petrochemical industry anchor Baton Rouge demand; flood-risk premium on insurance can pressure SFR cash-flow margins.', null, 'Medium'),
  ('corpus-christi-tx', 'Naval Air Station, port activity, and petrochemical employment anchor Corpus Christi rental demand with strong demand for SFR and townhome inventory.', null, 'High'),
  ('el-paso-tx', 'Military (Fort Bliss), university, and cross-border economy drive stable El Paso rental demand with below-average vacancy and strong rent growth relative to home prices.', null, 'High'),
  ('fayetteville-ar', 'University of Arkansas and Walmart HQ ecosystem drive strong Fayetteville rental demand, supporting above-average rent growth for Northwest Arkansas.', null, 'High'),
  ('fort-worth-tx', 'Fort Worth''s growing job base in manufacturing, logistics, and aerospace supports steady renter demand with vacancy trending below the DFW metro average.', null, 'High'),
  ('hattiesburg-ms', 'University of Southern Mississippi and healthcare sector anchor Hattiesburg rental demand, providing more stability than most Mississippi markets for buy-and-hold.', null, 'Medium'),
  ('houston-tx', 'Massive diverse economy, strong population inflow, and no state income tax support demand, but high supply additions and flood-zone vacancies keep rents competitive.', null, 'High'),
  ('jackson-ms', 'Mississippi''s state capital faces population contraction, water infrastructure issues, and high vacancy — very low entry prices but thin rent growth and above-average management risk.', null, 'Low'),
  ('kansas-city-ks', 'Cross-metro demand spillover from KC MO and growing industrial logistics employment support Kansas City KS rental demand, with below-average rents and yield potential.', null, 'Medium'),
  ('little-rock-ar', 'State capital, medical center, and university presence support stable Little Rock rental demand with low vacancy and favorable investor price-to-rent ratios.', null, 'Medium'),
  ('lubbock-tx', 'Texas Tech University anchors Lubbock rental demand, producing low price-to-rent ratios and above-average cash-flow potential for investors.', null, 'High'),
  ('mcallen-tx', 'Cross-border commerce and Rio Grande Valley healthcare growth drive McAllen renter demand, though supply additions and economic volatility add vacancy risk.', null, 'Medium'),
  ('new-orleans-la', 'Tourism economy and historic culture support demand, but hurricane risk, high insurance costs, and post-disaster vacancy spikes add meaningful volatility to NOLA cash flow.', null, 'Medium'),
  ('oklahoma-city-ok', 'OKC''s diversified energy, healthcare, and government employment base supports steady rental demand with vacancy well below national averages.', null, 'High'),
  ('shreveport-la', 'Gaming, healthcare, and Air Force base employment support Shreveport rental demand, but population decline and submarket variance require careful deal selection.', null, 'Medium'),
  ('tulsa-ok', 'Energy, aerospace, and healthcare drive Tulsa renter demand; low home prices and above-average yields make it a consistent cash-flow market.', null, 'High'),
  ('wichita-ks', 'Aviation manufacturing, healthcare, and university employment drive Wichita rental demand with low vacancy and strong price-to-rent ratios for cash-flow investors.', null, 'High'),
  ('akron-oh', 'University of Akron, healthcare, and polymer industry support rental demand; older housing stock and neighborhood variance require careful management.', null, 'Medium'),
  ('chicago-il', 'Massive metro with strong professional-renter demand, but very high property taxes, Cook County landlord-tenant laws, and price-to-rent ratios compress SFR investor returns.', null, 'High'),
  ('cincinnati-oh', 'P&G, healthcare, and university anchors support Cincinnati rental demand with tight inventory and consistently below-average vacancy for a Midwest metro.', null, 'High'),
  ('dayton-oh', 'Wright-Patt AFB, healthcare, and university sector provide stable Dayton renter base; low entry prices produce strong cash-flow metrics relative to purchase cost.', null, 'High'),
  ('des-moines-ia', 'Insurance, agriculture finance, and strong job growth support Des Moines rental demand; low vacancy and consistent rent appreciation make it a steady Midwest performer.', null, 'High'),
  ('detroit-mi', 'Detroit suburban demand is strong, but city-core investor risk requires granular zip-level diligence — high property taxes and insurance compress net yields.', null, 'Medium'),
  ('evansville-in', 'Healthcare, manufacturing, and university anchor Evansville rental demand; affordable entry prices and stable vacancy support consistent cash-flow performance.', null, 'Medium'),
  ('fort-wayne-in', 'Diversified manufacturing, healthcare, and insurance employment drive Fort Wayne rental demand with very low vacancy and strong rent growth relative to home prices.', null, 'High'),
  ('grand-rapids-mi', 'Diverse manufacturing, healthcare, and ArtPrize cultural economy drive Grand Rapids rental demand with very low vacancy and strong rent growth among Midwest peers.', null, 'High'),
  ('lansing-mi', 'Michigan State, state government, and GM Lansing anchor rental demand with affordable entry prices and steady vacancy for buy-and-hold investors.', null, 'Medium'),
  ('lexington-ky', 'University of Kentucky and horse industry drive Lexington rental demand; rising buyer prices are pushing more renters into the SFR market.', null, 'High'),
  ('louisville-ky', 'Healthcare, UPS hub, and bourbon industry anchor Louisville rental demand; moderate vacancy and growing professional-renter segment support above-average rent growth.', null, 'High'),
  ('madison-wi', 'University of Wisconsin, state government, and growing tech sector drive Madison rental demand with very low vacancy and consistently above-average rent growth.', null, 'High'),
  ('milwaukee-wi', 'Healthcare, manufacturing, and Marquette/UWM anchor Milwaukee rental demand; older housing stock and landlord-tenant regulations require careful underwriting.', null, 'Medium'),
  ('minneapolis-mn', 'Large corporate headquarters cluster, healthcare, and university anchor Minneapolis demand; tenant-protection ordinances and high property taxes require active underwriting.', null, 'High'),
  ('omaha-ne', 'Buffett-economy diversification across insurance, finance, and logistics drives Omaha rental demand with low unemployment, tight vacancy, and consistent rent growth.', null, 'High'),
  ('peoria-il', 'Caterpillar HQ, healthcare, and Bradley University anchor Peoria rental demand; affordable entry prices and low competition support cash-flow potential.', null, 'Medium'),
  ('rochester-mn', 'Mayo Clinic drives Rochester healthcare-worker rental demand with near-zero cyclicality and among the lowest vacancy rates of any Midwest mid-size market.', null, 'High'),
  ('rockford-il', 'Low home prices and stable healthcare/manufacturing employment support Rockford rental demand, though population softness and higher vacancy require active management.', null, 'Medium'),
  ('springfield-mo', 'Missouri State University, healthcare, and distribution center growth drive Springfield rental demand with favorable price-to-rent ratios for cash-flow investors.', null, 'High'),
  ('st-louis-mo', 'Healthcare, biotech, and logistics support St. Louis rental demand, but high property taxes and submarket variance significantly affect net yield by zip code.', null, 'Medium'),
  ('toledo-oh', 'Auto manufacturing and University of Toledo anchor demand, but population softness and submarket variance require disciplined Toledo deal selection.', null, 'Medium'),
  ('albuquerque-nm', 'Kirtland AFB, UNM, and Sandia Labs anchor Albuquerque rental demand with stable vacancy and favorable price-to-rent ratios relative to Mountain West peers.', null, 'High'),
  ('aurora-co', 'Buckley Space Force Base, VA hospital, and spillover demand from central Denver support Aurora rental demand with moderate vacancy and rent stability.', null, 'High'),
  ('boise-id', 'Boise''s rapid 2020-23 population surge pushed rents and prices sharply; 2024-25 correction is improving affordability but vacancy remains elevated from supply additions.', null, 'High'),
  ('casper-wy', 'Energy sector employment, state government, and Casper College support rental demand; low home prices and tight vacancy support solid cash-flow metrics.', null, 'Medium'),
  ('colorado-springs-co', 'Fort Carson, NORAD, and growing tech/defense sector support Colorado Springs rental demand with more affordable entry than Denver and favorable investor metrics.', null, 'High'),
  ('fort-collins-co', 'Colorado State University, clean-tech sector, and Millennial in-migration drive Fort Collins rental demand with very low vacancy and above-average rent growth.', null, 'High'),
  ('gilbert-az', 'Strong household income demographics, top-rated schools, and East Valley job growth drive Gilbert rental demand with below-average vacancy for the Phoenix metro.', null, 'High'),
  ('henderson-nv', 'Strong Henderson demographics, healthcare, and Las Vegas metro job growth support rental demand with slightly lower vacancy than Las Vegas proper.', null, 'High'),
  ('las-vegas-nv', 'Hospitality, convention, and logistics employment drive Las Vegas rental demand, but significant supply additions from 2022-24 are keeping rent growth flat.', null, 'High'),
  ('mesa-az', 'Mesa benefits from East Valley job growth and spillover demand from Scottsdale pricing; rents eased from 2022 peaks but vacancy is tightening.', null, 'High'),
  ('nampa-id', 'Treasure Valley spillover demand and more affordable prices than Boise make Nampa an emerging buy-and-hold market with improving rent growth as metro expands.', null, 'Medium'),
  ('ogden-ut', 'Hill AFB, manufacturing, and Weber State drive Ogden rental demand with more affordable rents than SLC or Provo and favorable price-to-rent ratios.', null, 'High'),
  ('provo-ut', 'BYU, Utah Valley University, and tech sector in-migration create strong Provo rental demand with consistently low vacancy among Utah metro markets.', null, 'High'),
  ('reno-nv', 'Tesla Gigafactory, logistics, and remote-worker migration boosted Reno rental demand sharply; 2024-25 correction is reducing rent growth as new supply absorbs.', null, 'High'),
  ('salt-lake-city-ut', 'Tech corridor growth, strong in-migration, and LDS institutional anchors drive Salt Lake City rental demand with low unemployment and tightening vacancy.', null, 'High'),
  ('tucson-az', 'University of Arizona, military, and healthcare anchor Tucson demand; rent softness from 2024-25 supply surge is correcting, with improving vacancy trends.', null, 'High'),
  ('bakersfield-ca', 'Oil, agriculture, and logistics drive Bakersfield rental demand with lower home prices and more favorable cash-flow metrics than coastal California markets.', null, 'High'),
  ('eugene-or', 'University of Oregon drives Eugene rental demand with consistent student and young-professional renter base; lower entry prices than Portland with better yield potential.', null, 'High'),
  ('fresno-ca', 'Central Valley ag economy, healthcare, and Fresno State anchor rental demand; below-average rents relative to California but improving yield potential versus coastal peers.', null, 'High'),
  ('los-angeles-ca', 'Massive entertainment, tech, and healthcare economy drives LA rental demand, but extreme home prices, tenant-protection laws, and price-to-rent ratios challenge SFR investor returns.', null, 'High'),
  ('portland-or', 'Tech, Nike/adidas ecosystem, and healthcare anchor Portland demand, but aggressive rent-control policies, tenant protections, and high vacancy from 2022-24 supply challenge investor returns.', null, 'High'),
  ('riverside-ca', 'Inland Empire logistics boom, UC Riverside, and LA market spillover drive Riverside rental demand with tightening vacancy and improving rent growth.', null, 'High'),
  ('sacramento-ca', 'State government, UC Davis spillover, and Bay Area affordability migration drive Sacramento rental demand with stable vacancy and more viable investor metrics than coastal CA.', null, 'High'),
  ('salem-or', 'State government, Willamette University, and Portland spillover demand support Salem rental activity with affordable entry prices and moderate vacancy.', null, 'Medium'),
  ('san-diego-ca', 'Military, biotech, and tourism anchor San Diego demand with among the nation''s lowest vacancy rates; price-to-rent ratio is one of the highest, limiting cash-flow.', null, 'High'),
  ('seattle-wa', 'Amazon, Microsoft, and tech sector drive Seattle rental demand with very low vacancy, but high home prices, capital gains taxes, and tenant protections compress investor margins.', null, 'High'),
  ('spokane-wa', 'Washington State-Spokane, Gonzaga, and healthcare sector anchor Spokane rental demand with favorable price-to-rent ratios and low vacancy relative to Pacific peers.', null, 'High'),
  ('stockton-ca', 'Delta College, logistics, and Bay Area spillover demand support Stockton rental activity; lower entry prices improve investor metrics but vacancy is above San Joaquin average.', null, 'Medium'),
  ('tacoma-wa', 'Joint Base Lewis-McChord, University of Washington Tacoma, and Seattle-spillover affordability demand drive Tacoma rental growth with improving price-to-rent metrics.', null, 'High'),
  ('albany-ny', 'State government, healthcare, and University at Albany provide Albany with a stable renter base resistant to economic cycles.', null, 'High'),
  ('allentown-pa', 'Lehigh Valley warehousing boom, healthcare, and commuter demand from NYC corridor drive Allentown rental growth with tightening vacancy and accelerating rent appreciation.', null, 'High'),
  ('baltimore-md', 'Johns Hopkins, healthcare, and port employment anchor Baltimore demand; zip-code variance is extreme — submarket selection is the single biggest determinant of investor outcome.', null, 'Medium'),
  ('bridgeport-ct', 'Fairfield County spillover, healthcare, and commuter demand from NYC corridor support Bridgeport rental activity with improving fundamentals in select neighborhoods.', null, 'Medium'),
  ('buffalo-ny', 'UB medical campus expansion, healthcare, and urban revitalization drive Buffalo rental demand; low entry prices and improving neighborhoods create strong yield potential.', null, 'High'),
  ('camden-nj', 'Campbell Soup HQ, hospital anchors, and Philly-spillover demand support Camden rental activity; very low entry prices but above-average vacancy and management risk require diligence.', null, 'Medium'),
  ('fredericksburg-va', 'DC-metro commuter demand, Marine Corps Base Quantico, and UMW drive Fredericksburg rental demand with very low vacancy and consistent rent appreciation.', null, 'High'),
  ('hartford-ct', 'Insurance industry, state government, and Trinity/UConn Health anchor Hartford demand; rising landlord costs and aging stock require careful underwriting.', null, 'Medium'),
  ('philadelphia-pa', 'Massive medical, education, and finance sector drive Philly rental demand; strong demand in suburban corridors and improving city neighborhoods supports consistent rent growth.', null, 'High'),
  ('roanoke-va', 'Healthcare, Virginia Tech corporate spinoffs, and Blue Ridge outdoor economy support Roanoke rental demand with affordable entry prices and low vacancy.', null, 'High'),
  ('rochester-ny', 'University of Rochester, Kodak legacy sector, and healthcare anchor Rochester demand; low acquisition prices and stable vacancy support above-average cash-flow metrics.', null, 'High'),
  ('silver-spring-md', 'DC-metro proximity, Discovery/FDA anchors, and Metro Red Line access drive Silver Spring rental demand with low vacancy and consistent premium for affordability-seeking renters.', null, 'High'),
  ('springfield-ma', 'Baystate Health, Western New England University, and affordable rents relative to Boston drive Springfield investor interest with improving vacancy trends.', null, 'Medium'),
  ('syracuse-ny', 'Syracuse University, healthcare, and defense manufacturing anchor rental demand; below-average rents and home prices produce favorable price-to-rent ratios.', null, 'High'),
  ('trenton-nj', 'State government and Philadelphia-metro spillover demand support Trenton rental activity; improving neighborhood fundamentals in select areas increase investor opportunity.', null, 'Medium'),
  ('worcester-ma', 'UMass Medical, strong multi-university cluster, and Boston-overspill demand drive Worcester rental growth with tightening vacancy and above-average appreciation among MA markets.', null, 'High')
on conflict (market_id) do update set
  ltr_note       = excluded.ltr_note,
  ltr_source_url = excluded.ltr_source_url,
  confidence     = coalesce(public.market_premium.confidence, excluded.confidence),
  updated_at     = now();
